import React from 'react'
import NODATA from '../../../../public/images/no-data.jpg'

import Image from 'next/image'
type Props = {}

const NotFound = (props: Props) => {
  return (
    <div className='flex flex-col min-h-[70vh] w-full justify-center items-center gap-12'>
        {/* <StrokeEarth /> */}
        <Image 
            src={NODATA}
            alt='no-data'
            height={400}
            width={400}
            // className='w-fit'
        />
        <div className='flex flex-col items-center justify-center text-center'>
            <p className='text-3xl font-semibold text-primary'>
                Noting to see here... 
            </p>
            <p className='text-base font-normal dark:text-secondary'>
                So here is a random image generated by <span className='text-vivid'>Creative AI</span>
            </p>
        </div>
    </div>
  )
}

export default NotFound